Feature 3.0
BlueXTX/BlueXT.MobileMonitoring pull request #5
Opened 2023-07-14 09:52 UTC by BlueXTX

- Добавил хранение данных в Postgres
- Добавил репозитории с использованием Dapper
- Добавил миграции базы данных

2023-07-17 10:22 UTC, SergerGood requested changes

2023-07-17 10:43 UTC, BlueXTX commented on aspnet-core/src/BlueXT.MobileMonitoring.EntityFrameworkCore/Configurations/DeviceStatisticConfiguration.cs
> +        builder.Property(x => x.IsDeleted).HasColumnName("is_deleted");
Дата создания в итоге пригодилась для #6, а дата удаления пока не используется

2023-07-17 10:44 UTC, BlueXTX commented on aspnet-core/src/BlueXT.MobileMonitoring.EntityFrameworkCore/Configurations/DeviceStatisticConfiguration.cs
> +        builder.ToTable(MobileMonitoringConsts.DbTablePrefix + "device_statistic");
Для исключения конфликтов модулей, которые используют одну БД

2023-07-17 10:45 UTC, BlueXTX commented on aspnet-core/src/BlueXT.MobileMonitoring.Dapper/Repositories/DapperDeviceStatisticRepository.cs
> +    public Task<List<DeviceStatistic>> GetListAsync(bool includeDetails = false, CancellationToken cancellationToken = new()) => throw new NotImplementedException();
Райдер нагенерил такое, интерфейс определяет дефолтное значение как new CancellationToken(). Заменю на default.

2023-07-17 10:51 UTC, BlueXTX commented on aspnet-core/src/BlueXT.MobileMonitoring.EntityFrameworkCore/Configurations/DeviceStatisticConfiguration.cs
В данном проекте EF используется для внутренних сервисов ABP, а также для миграций. Могу дополнительно написать миграции на FluentMigrations.

2023-07-17 11:13 UTC, BlueXTX commented on aspnet-core/src/BlueXT.MobileMonitoring.Application/DeviceStatistics/DeviceStatisticService.cs
> +    /// Создать сущность.
Обновил документацию

2023-07-17 11:13 UTC, BlueXTX commented on aspnet-core/src/BlueXT.MobileMonitoring.EntityFrameworkCore/Configurations/DeviceStatisticConfiguration.cs
Создал

2023-07-17 11:14 UTC, BlueXTX commented on aspnet-core/src/BlueXT.MobileMonitoring.Dapper/Repositories/DapperDeviceStatisticRepository.cs
> +    public Task<List<DeviceStatistic>> GetListAsync(bool includeDetails = false, CancellationToken cancellationToken = new()) => throw new NotImplementedException();
Изменил на default

2023-07-17 11:21 UTC, SergerGood commented on aspnet-core/src/BlueXT.MobileMonitoring.Application/DeviceStatistics/DeviceStatisticService.cs
> +    /// Создать сущность.
кажется еще в репозитории видел

2023-07-17 11:25 UTC, SergerGood commented on aspnet-core/src/BlueXT.MobileMonitoring.EntityFrameworkCore/Configurations/DeviceStatisticConfiguration.cs
> +        builder.ToTable(MobileMonitoringConsts.DbTablePrefix + "device_statistic");
мне кажется тут есть стандартные средства. Например использовать разные БД, или схему

2023-07-17 11:29 UTC, BlueXTX commented on aspnet-core/src/BlueXT.MobileMonitoring.EntityFrameworkCore/Configurations/DeviceStatisticConfiguration.cs
> +        builder.ToTable(MobileMonitoringConsts.DbTablePrefix + "device_statistic");
Да, но здесь рассматривался пессимистичный сценарий, в котором мы имеем доступ к одной БД и схеме

2023-07-17 11:31 UTC, SergerGood commented on aspnet-core/src/BlueXT.MobileMonitoring.EntityFrameworkCore/Configurations/DeviceStatisticConfiguration.cs
> +        builder.Property(x => x.IsDeleted).HasColumnName("is_deleted");
дата создания... не понял, как пригодится
а вот удаление, пока не используется говоришь, но при этом в методах репозитория вполне себе используется

2023-07-17 11:35 UTC, SergerGood commented on aspnet-core/src/BlueXT.MobileMonitoring.EntityFrameworkCore/Configurations/DeviceStatisticConfiguration.cs
> +        builder.ToTable(MobileMonitoringConsts.DbTablePrefix + "device_statistic");
ну тут вроде не должно быть проблем, пока все в наших руках) 
Ладно, я понял почему, единственное не согласен с таким решением, пока нет явных ограничений. Оставим так

2023-07-17 11:47 UTC, BlueXTX commented on aspnet-core/src/BlueXT.MobileMonitoring.EntityFrameworkCore/Configurations/DeviceStatisticConfiguration.cs
> +        builder.Property(x => x.IsDeleted).HasColumnName("is_deleted");
Сейчас выяснил, что дата создания события не равна дате вызова эндпоинта на создание события. Исходя из этого дата создания тоже не используется. Дата удаления в репозитории реализована, но в бизнес-логике не используется.

2023-07-17 15:17 UTC, BlueXTX commented on aspnet-core/src/BlueXT.MobileMonitoring.EntityFrameworkCore/Configurations/DeviceStatisticConfiguration.cs
> +        builder.Property(x => x.IsDeleted).HasColumnName("is_deleted");
Удалил аудит

2023-07-18 06:38 UTC, SergerGood approved these changes

2023-07-18 06:47 UTC, merged