Version 4.0
BlueXTX/BlueXT.MobileMonitoring pull request #6
Opened 2023-07-17 09:13 UTC by BlueXTX

- Добавлены тесты

2023-07-17 10:40 UTC, SergerGood requested changes

2023-07-17 10:40 UTC, SergerGood commented on aspnet-core/src/BlueXT.MobileMonitoring.Application.Contracts/DeviceEvents/CreateOrUpdateDeviceEventDto.cs
> +    public string? Description { get; set; } = string.Empty;
тут наверное описание это какое-то значение для UI которое получается на основании самого события

2023-07-17 10:40 UTC, SergerGood commented on aspnet-core/src/BlueXT.MobileMonitoring.Application/DeviceEvents/Validators/CreateOrUpdateDeviceEventDtoValidator.cs
> +        RuleFor(x => x.Name).NotEmpty().MaximumLength(maximumLength: 128);
по описанию не 50?

2023-07-17 10:40 UTC, SergerGood commented on aspnet-core/src/BlueXT.MobileMonitoring.Application.Contracts/DeviceEvents/CreateOrUpdateDeviceEventDto.cs
> +public class CreateOrUpdateDeviceEventDto
А почему тут даты нет?

2023-07-17 10:40 UTC, SergerGood commented on aspnet-core/test/BlueXT.MobileMonitoring.Application.Tests/Samples/DeviceEventServiceTests.cs
> +using Shouldly;
а почему не FluentAssertion?

2023-07-17 10:40 UTC, SergerGood commented on aspnet-core/test/BlueXT.MobileMonitoring.Application.Tests/Samples/DeviceEventServiceTests.cs
> +public sealed class DeviceEventServiceTests : MobileMonitoringApplicationTestBase
Тесты тоже документируются

2023-07-17 10:40 UTC, SergerGood commented on aspnet-core/test/BlueXT.MobileMonitoring.Application.Tests/Samples/DeviceEventServiceTests.cs
А интеграционные тесты будут?

2023-07-17 10:54 UTC, BlueXTX commented on aspnet-core/src/BlueXT.MobileMonitoring.Application.Contracts/DeviceEvents/CreateOrUpdateDeviceEventDto.cs
> +    public string? Description { get; set; } = string.Empty;
Значит это поле не нужно?

2023-07-17 10:56 UTC, BlueXTX commented on aspnet-core/test/BlueXT.MobileMonitoring.Application.Tests/Samples/DeviceEventServiceTests.cs
> +    public async Task CreateAsync_WithValidDto_ShouldReturnEntity()
Не нашел в документах информацию о именовании тестов. Прошу прислать.

2023-07-17 10:57 UTC, BlueXTX commented on aspnet-core/test/BlueXT.MobileMonitoring.Application.Tests/Samples/DeviceEventServiceTests.cs
> +using Shouldly;
Заменю на FluentAssertions

2023-07-17 10:57 UTC, BlueXTX commented on aspnet-core/test/BlueXT.MobileMonitoring.Application.Tests/Samples/DeviceEventServiceTests.cs
Да

2023-07-17 11:02 UTC, SergerGood commented on aspnet-core/test/BlueXT.MobileMonitoring.Application.Tests/Samples/DeviceEventServiceTests.cs
> +using Shouldly;
да мне для начала было просто почему, может ты работал с обоими библиотеками

2023-07-17 11:05 UTC, SergerGood commented on aspnet-core/src/BlueXT.MobileMonitoring.Application.Contracts/DeviceEvents/CreateOrUpdateDeviceEventDto.cs
> +    public string? Description { get; set; } = string.Empty;
там по заданию его вроде бы даже нет

2023-07-17 11:40 UTC, SergerGood commented on aspnet-core/test/BlueXT.MobileMonitoring.Application.Tests/Samples/DeviceEventServiceTests.cs
> +    public async Task CreateAsync_WithValidDto_ShouldReturnEntity()
Так то стандартно ИмяМетода_Условие_Результат.
Просто казалось что второй подход это ShouldЧтоМогуСделатьПриУсловии

2023-07-17 11:50 UTC, BlueXTX commented on aspnet-core/src/BlueXT.MobileMonitoring.Application.Contracts/DeviceEvents/CreateOrUpdateDeviceEventDto.cs
> +    public string? Description { get; set; } = string.Empty;
На скриншоте описание есть, а в примере ответа нет.

2023-07-17 11:51 UTC, BlueXTX commented on aspnet-core/test/BlueXT.MobileMonitoring.Application.Tests/Samples/DeviceEventServiceTests.cs
> +using Shouldly;
В шаблоне была Shouldly, по базовому api практически то же самое, но я предпочитаю FluentAssertions

2023-07-17 11:56 UTC, SergerGood commented on aspnet-core/src/BlueXT.MobileMonitoring.Application.Contracts/DeviceEvents/CreateOrUpdateDeviceEventDto.cs
> +    public string? Description { get; set; } = string.Empty;
апи все таки первоначально, UI проговаривали что это примерная реализация. Причем как я написал, там такой UI что его можно сделать без бэка

2023-07-17 11:56 UTC, SergerGood commented on aspnet-core/test/BlueXT.MobileMonitoring.Application.Tests/Samples/DeviceEventServiceTests.cs
> +using Shouldly;
хорошо

2023-07-17 12:42 UTC, SergerGood commented on aspnet-core/test/BlueXT.MobileMonitoring.Application.Tests/Samples/DeviceEventServiceTests.cs
> +    public async Task CreateAsync_WithValidDto_ShouldReturnEntity()
нет, особых требований нет

2023-07-17 15:23 UTC, BlueXTX commented on aspnet-core/src/BlueXT.MobileMonitoring.Application/DeviceEvents/Validators/CreateOrUpdateDeviceEventDtoValidator.cs
> +        RuleFor(x => x.Name).NotEmpty().MaximumLength(maximumLength: 128);
Изменил на 50

2023-07-17 15:23 UTC, BlueXTX commented on aspnet-core/src/BlueXT.MobileMonitoring.Application.Contracts/DeviceEvents/CreateOrUpdateDeviceEventDto.cs
> +public class CreateOrUpdateDeviceEventDto
Ошибка. Добавил поле CreationDate.

2023-07-18 12:14 UTC, SergerGood commented on aspnet-core/test/BlueXT.MobileMonitoring.Application.Tests/Samples/DeviceEventServiceTests.cs
> +using Shouldly;
не докомител? Пока не нашел

2023-07-18 12:21 UTC, OksanaBelikInfotecs commented on angular/src/app/device-events/device-events.component.ts
> +        this.deviceStatisticService.getByDeviceId(this.deviceId).subscribe(response => {
А пока эти два запроса грузятся, может пользователю как-то сказать, что мы упорно трудимся, но еще не готовы дать ему ответ ?

2023-07-18 12:21 UTC, OksanaBelikInfotecs commented on angular/src/app/device-statistics/device-statistics.component.ts
> +        private offcanvasService: NgbOffcanvas,
А почему этот сервис не readonly? Ну и deviceStatisticService

2023-07-18 12:21 UTC, OksanaBelikInfotecs commented on angular/src/app/device-events/device-events.component.ts
> +        this.deviceEventsService.getListByDeviceId(this.deviceId).subscribe(response => {
А может быть такое, что устройства с таким Id  нет?

2023-07-19 11:45 UTC, BlueXTX commented on aspnet-core/test/BlueXT.MobileMonitoring.Application.Tests/Samples/DeviceEventServiceTests.cs
> +public sealed class DeviceEventServiceTests : MobileMonitoringApplicationTestBase
Задокументировал

2023-07-19 11:46 UTC, BlueXTX commented on angular/src/app/device-events/device-events.component.ts
> +        this.deviceEventsService.getListByDeviceId(this.deviceId).subscribe(response => {
Нет, т.к. на экране выводятся все доступные устройства

2023-07-19 11:47 UTC, BlueXTX commented on angular/src/app/device-statistics/device-statistics.component.ts
> +        private offcanvasService: NgbOffcanvas,
Не досмотрел. Пометил как readonly.

2023-07-19 12:02 UTC, BlueXTX commented on angular/src/app/device-events/device-events.component.ts
> +        this.deviceStatisticService.getByDeviceId(this.deviceId).subscribe(response => {
Добавил индикатор загрузки

2023-07-19 12:17 UTC, BlueXTX commented on angular/src/app/device-events/device-events.component.ts
> +        this.deviceEventsService.getListByDeviceId(this.deviceId).subscribe(response => {
Под доступными устройствами я подразумеваю те, которые были созданы заранее. А панель событий открывается только по клику на устройство в таблице.

2023-07-19 12:25 UTC, OksanaBelikInfotecs commented on angular/src/app/device-events/device-events.component.ts
> +        this.deviceEventsService.getListByDeviceId(this.deviceId).subscribe(response => {
А если из другого браузера удалить? А в первом не обновлять и открыть?

2023-07-19 12:29 UTC, OksanaBelikInfotecs approved these changes

2023-07-20 06:29 UTC, merged