Version 5.0
BlueXTX/BlueXT.MobileMonitoring pull request #8
Opened 2023-07-21 11:27 UTC by BlueXTX

- Добавил скрипты для сборки в TeamCity или локально
- Реализовал новый функционал api

2023-07-24 17:47 UTC, SergerGood requested changes

2023-07-24 17:47 UTC, SergerGood commented on aspnet-core/Dockerfile
> +RUN dotnet build "BlueXT.MobileMonitoring.HttpApi.Host.csproj" -c Release -o /app/build
раз уж рестор соптимизировали то и билд можно с помощью --no-restore

2023-07-24 17:47 UTC, SergerGood commented on aspnet-core/src/BlueXT.MobileMonitoring.HttpApi.Host/BlueXT.MobileMonitoring.HttpApi.Host.csproj
> +        <Content Remove="Logs\**" />
не могу, глаз режет, давай удалим

2023-07-24 17:47 UTC, SergerGood commented on aspnet-core/src/BlueXT.MobileMonitoring.Application/DeviceEvents/DeviceEventService.cs
> +        var deviceStatistic = await _deviceStatisticRepository.GetByDeviceId(deviceId);
А зачем объект получать?

2023-07-24 17:47 UTC, SergerGood commented on aspnet-core/src/BlueXT.MobileMonitoring.Application/DeviceStatistics/DeviceStatisticService.cs
>          IRepository<DeviceStatistic, Guid> baseRepository,
я вот смотрю на разнобразие репозиториев и чисто визуально не понимаю в чем хитрость. Базовый на сколько я помню обязательный для базового класса. Но дальше. Почему подход либо с разными интерфейсами?

2023-07-24 17:47 UTC, SergerGood commented on aspnet-core/src/BlueXT.MobileMonitoring.Application/DeviceStatistics/DeviceStatisticService.cs
>      {
Сложно понять когда UOW уже реализован в дргом комите, не понятна логика его работы. Когда он инициализируется и происходит коммит?

2023-07-24 17:47 UTC, SergerGood commented on aspnet-core/src/BlueXT.MobileMonitoring.Application/DeviceStatistics/DeviceStatisticService.cs
> +        foreach (var entityDeviceEvent in entity.DeviceEvents) entityDeviceEvent.DeviceStatisticId = insertedEntity.Id;
Если у нас DeviceStatistic владеет DeviceEvents, то почему идентификаторы проставляются здесь?

2023-07-25 07:24 UTC, BlueXTX commented on aspnet-core/src/BlueXT.MobileMonitoring.Application/DeviceStatistics/DeviceStatisticService.cs
>      {
https://docs.abp.io/en/abp/latest/Unit-Of-Work#:~:text=A%20UOW%20automatically%20begins%20for%20these%20methods%20except%20if%20there%20is%20already%20a%20surrounding%20(ambient)%20UOW%20in%20action.%20Examples%3B

2023-07-25 07:40 UTC, BlueXTX commented on aspnet-core/src/BlueXT.MobileMonitoring.Application/DeviceEvents/DeviceEventService.cs
> +        var deviceStatistic = await _deviceStatisticRepository.GetByDeviceId(deviceId);
Потому что мы выполняем поиск не по deviceId, а по Id сущности DeviceStatistic

2023-07-25 07:42 UTC, BlueXTX commented on aspnet-core/src/BlueXT.MobileMonitoring.HttpApi.Host/BlueXT.MobileMonitoring.HttpApi.Host.csproj
> +        <Content Remove="Logs\**" />
Удалил

2023-07-25 07:42 UTC, BlueXTX commented on scripts/build-api.sh
Удалил

2023-07-25 07:44 UTC, BlueXTX commented on aspnet-core/Dockerfile
> +RUN dotnet build "BlueXT.MobileMonitoring.HttpApi.Host.csproj" -c Release -o /app/build
Добавил

2023-07-25 07:47 UTC, BlueXTX commented on aspnet-core/src/BlueXT.MobileMonitoring.Application/DeviceStatistics/DeviceStatisticService.cs
>          IRepository<DeviceStatistic, Guid> baseRepository,
IDeviceStatisticRepository предоставляет дополнительные методы репозитория. Мы не можем прокинуть его в базовый класс, т.к. он наследуется не от IRepository, а от IBasicRepository(для того, чтобы не реализовывать все возможные методы. Исходя из вышесказанного у нас получается не очень красивый код, но это избавляет нас от необходимости реализовывать все методы IRepository.

2023-07-25 08:09 UTC, BlueXTX commented on aspnet-core/Dockerfile
> +RUN dotnet publish "BlueXT.MobileMonitoring.HttpApi.Host.csproj" -c Release -o /app/publish /p:UseAppHost=false
Не совсем понял вопрос. Rider предложил такой Dockerfile.

2023-07-25 11:05 UTC, SergerGood commented on aspnet-core/src/BlueXT.MobileMonitoring.Application/DeviceEvents/DeviceEventService.cs
> +        var deviceStatistic = await _deviceStatisticRepository.GetByDeviceId(deviceId);
я в твоей модели запутался, а можешь диаграмму классов накидать. Тут кажется plantUML поддержали. Я просто пока не понимаю зачем так, или просто не понимаю)

2023-07-25 11:14 UTC, SergerGood commented on aspnet-core/src/BlueXT.MobileMonitoring.Application/DeviceStatistics/DeviceStatisticService.cs
>          IRepository<DeviceStatistic, Guid> baseRepository,
все таки выглядит как сложная грань, которую надо понимать. Пока выглядит что у меня есть сущность IRepository, IBasicRepository и еще частные на подобие IDeviceStatisticRepository

2023-07-25 11:17 UTC, SergerGood commented on aspnet-core/src/BlueXT.MobileMonitoring.Application/DeviceStatistics/DeviceStatisticService.cs
>      {
Почитал, до конца все равно не понятно) есть нюансы, которые бы хотелось спросить, но получается ответ звучит как уже реализовано и чтобы понять надо разбираться.

2023-07-25 11:35 UTC, SergerGood commented on aspnet-core/src/BlueXT.MobileMonitoring.Application/DeviceStatistics/DeviceStatisticService.cs
> +        foreach (var entityDeviceEvent in entity.DeviceEvents) entityDeviceEvent.DeviceStatisticId = insertedEntity.Id;
наверное мысль у меня такая: есть объект DeviceStatistic и у него есть DeviceEvents, но с ними работают разные репозитории. Т.е. мне всегда надо помнить что чтобы получить консистентный объект, мне всегда надо сделать две выборки или два метода. Не пытаемся ли мы здесь логику ORM накрутить, но не до конца?

2023-07-25 11:46 UTC, BlueXTX commented on aspnet-core/src/BlueXT.MobileMonitoring.Application/DeviceEvents/DeviceEventService.cs
> +        var deviceStatistic = await _deviceStatisticRepository.GetByDeviceId(deviceId);
![image](https://github.com/BlueXTX/BlueXT.MobileMonitoring/assets/48766766/691489b0-5fc2-4663-b461-5b91047044a2)

2023-07-25 12:48 UTC, BlueXTX commented on aspnet-core/src/BlueXT.MobileMonitoring.Application/DeviceStatistics/DeviceStatisticService.cs
> +        foreach (var entityDeviceEvent in entity.DeviceEvents) entityDeviceEvent.DeviceStatisticId = insertedEntity.Id;
А куда вынести эту логику? В репозиторий? Если так, то нам будет необходимо инжектить репозиторий в репозиторий.

2023-07-25 12:53 UTC, BlueXTX commented on aspnet-core/Dockerfile
> +RUN dotnet publish "BlueXT.MobileMonitoring.HttpApi.Host.csproj" -c Release -o /app/publish /p:UseAppHost=false
Да, но можно оставить, чтобы в production сборке тесты прогонять

2023-07-25 14:48 UTC, SergerGood commented on aspnet-core/src/BlueXT.MobileMonitoring.Application/DeviceStatistics/DeviceStatisticService.cs
> +        foreach (var entityDeviceEvent in entity.DeviceEvents) entityDeviceEvent.DeviceStatisticId = insertedEntity.Id;
ну может не стоит связывать тогда сущности? На этом уровне

2023-07-25 14:48 UTC, SergerGood commented on aspnet-core/src/BlueXT.MobileMonitoring.Application/DeviceEvents/DeviceEventService.cs
> +        var deviceStatistic = await _deviceStatisticRepository.GetByDeviceId(deviceId);
проговаривали что id здесь лишний. Будем избавлятся?

2023-07-25 14:49 UTC, BlueXTX commented on aspnet-core/src/BlueXT.MobileMonitoring.Application/DeviceEvents/DeviceEventService.cs
> +        var deviceStatistic = await _deviceStatisticRepository.GetByDeviceId(deviceId);
Если требуется, то да)

2023-07-25 14:52 UTC, BlueXTX commented on aspnet-core/src/BlueXT.MobileMonitoring.Application/DeviceEvents/DeviceEventService.cs
> +        var deviceStatistic = await _deviceStatisticRepository.GetByDeviceId(deviceId);
Завел issue #10

2023-07-26 09:26 UTC, BlueXTX commented on aspnet-core/src/BlueXT.MobileMonitoring.Application/DeviceStatistics/DeviceStatisticService.cs
> +        foreach (var entityDeviceEvent in entity.DeviceEvents) entityDeviceEvent.DeviceStatisticId = insertedEntity.Id;
Удалил связь

2023-07-26 10:26 UTC, SergerGood commented on aspnet-core/src/BlueXT.MobileMonitoring.Application/DeviceEvents/DeviceEventService.cs
> +        => _mapper.Map<List<DeviceEvent>, List<DeviceEventDto>>(await Repository.GetListAsync(x => x.DeviceId == deviceId));
просьба не пытаться написать все в одну строчку, тем более когда более чем одно действие

2023-07-26 10:26 UTC, SergerGood approved these changes

2023-07-26 10:38 UTC, BlueXTX commented on aspnet-core/src/BlueXT.MobileMonitoring.Application/DeviceEvents/DeviceEventService.cs
> +        => _mapper.Map<List<DeviceEvent>, List<DeviceEventDto>>(await Repository.GetListAsync(x => x.DeviceId == deviceId));
Исправил

2023-07-26 10:47 UTC, merged